version: '3'

services:

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 20s 
    command: /bin/sh -c "nginx -g 'daemon off;'"
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on: 
      - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    depends_on: 
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /data/application/init-script.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/ini-sql:/data/application
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network


networks:
  node-network:
    driver: bridge